const bcrypt = require('bcrypt');

const data = {
  users: [
    {
      name: "Nasema",
      email: "adminTest5@gmail.com",
      displayName: "Nasema",
      displayRoleType: "Admin",
      displayImage: "./images/1.png",
      greeting: "Welcome I am Kassie Your Admin!",
      password: bcrypt.hashSync("djyeTesting123", 10),
      isAdmin: true,
    },
    {
      name: "Omid",
      email: "admin@gmail.com",
      displayName: "Omid",
      displayRoleType: "Admin",
      displayImage: "./images/2.png",
      greeting: "Welcome I am Karla Your Admin!",
      password: bcrypt.hashSync("KKTesting1234", 10),
      isAdmin: true,
    },
    {
      name: "Tommy",
      email: "tommy@gmail.com",
      displayName: "Tommy",
      displayRoleType: "User",
      displayImage: "./images/3.png",
      greeting: "Welcome I am Tommy!",
      password: bcrypt.hashSync("testing123", 10),
      isAdmin: false,
    },
    {
      name: "Sally",
      email: "sally@gmail.com",
      displayName: "Sally",
      displayRoleType: "User",
      displayImage:"./images/4.png",
      greeting: "Welcome I am Sally!",
      password: bcrypt.hashSync("testing1234", 10),
      isAdmin: false,
    },
    {
      name: "Billy",
      email: "billyTest@gmail.com",
      displayName: "Billy",
      displayRoleType: "User",
      displayImage:"./images/5.png",
      greeting: "Welcome I am Billy!",
      password: bcrypt.hashSync("testing12345", 10),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Wing Zero Gundam EndlessWaltz",
      category: "Custom Gundam",
      image: "./images/products/7.png",
      price: 320,
      countInStock: 10,
      brand: "Bandai",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Gundam model kit",
    },
    {
      name: "Justice Gundam",
      category: "Custom Gundam",
      image: "./images/products/8.png",
      price: 200,
      countInStock: 20,
      brand: "Bandai",
      rating: 4.0,
      numReviews: 10,
      description: "high quality Gundam model kit",
    },
    {
      name: "StrikeFreedom Gundam",
      category: "Custom Gundam",
      image: "./images/products/9.png",
      price: 420,
      countInStock: 0,
      brand: "Bandai",
      rating: 4.8,
      numReviews: 17,
      description: "high quality Gundam model kit",
    },
    {
      name: "Strike Rouge Gundam",
      category: "Plastic Model Kit",
      image: "./images/products/10.png",
      price: 98,
      countInStock: 15,
      brand: "Sunrise",
      rating: 4.5,
      numReviews: 14,
      description: "high quality Gundam model kit plastic",
    },
    {
      name: "Buster Gundam",
      category: "Plastic Model Kit",
      image: "./images/products/11.png",
      price: 165,
      countInStock: 5,
      brand: "Sunrise",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Gundam model kit plastic",
    },
    {
      name: "Destiny Gundam",
      category: "Custom Gundam",
      image: "./images/products/12.png",
      price: 339,
      countInStock: 12,
      brand: "Bandai",
      rating: 4.5,
      numReviews: 15,
      description: "high quality Gundam model kit",
    },
  ],
};

module.exports = data;